# Generated by Django 5.0.6 on 2026-06-07 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='品牌名称')),
                ('country', models.CharField(max_length=50, verbose_name='所属国家')),
                ('brand_type', models.CharField(choices=[('domestic', '国产'), ('joint', '合资'), ('foreign', '进口')], default='domestic', max_length=20, verbose_name='品牌类型')),
                ('founded_year', models.IntegerField(default=2010, verbose_name='成立年份')),
                ('market_share', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='市场份额(%)')),
            ],
            options={
                'verbose_name': '汽车品牌',
                'verbose_name_plural': '汽车品牌',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='区域名称')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('tier', models.IntegerField(choices=[(1, '一线'), (2, '二线'), (3, '三线'), (4, '四线'), (5, '五线')], default=2, verbose_name='城市等级')),
                ('population', models.IntegerField(default=500, verbose_name='人口数量(万)')),
                ('gdp', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GDP(亿元)')),
            ],
            options={
                'verbose_name': '销售区域',
                'verbose_name_plural': '销售区域',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='经销商名称')),
                ('dealer_type', models.CharField(choices=[('4s', '4S店'), ('experience', '体验中心'), ('direct', '直营店'), ('agency', '代理商')], default='4s', max_length=20, verbose_name='经销商类型')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系方式')),
                ('store_size', models.IntegerField(default=500, verbose_name='店面面积(平方米)')),
                ('staff_count', models.IntegerField(default=20, verbose_name='员工数量')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3, verbose_name='评分')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.brand', verbose_name='经营品牌')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.region', verbose_name='所在区域')),
            ],
            options={
                'verbose_name': '经销商',
                'verbose_name_plural': '经销商',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('age_group', models.CharField(choices=[('18-25', '18-25岁'), ('26-35', '26-35岁'), ('36-45', '36-45岁'), ('46-55', '46-55岁'), ('55+', '55岁以上')], default='26-35', max_length=20, verbose_name='年龄段')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('occupation', models.CharField(blank=True, max_length=50, verbose_name='职业')),
                ('income_level', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=2, verbose_name='收入水平')),
                ('is_returning', models.BooleanField(default=False, verbose_name='是否回头客')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.region', verbose_name='所在区域')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='车型名称')),
                ('vehicle_type', models.CharField(choices=[('sedan', '轿车'), ('suv', 'SUV'), ('mpv', 'MPV'), ('truck', '皮卡')], default='sedan', max_length=20, verbose_name='车辆类型')),
                ('power_type', models.CharField(choices=[('bev', '纯电动'), ('phev', '插电混动'), ('erev', '增程式'), ('fcev', '燃料电池')], default='bev', max_length=20, verbose_name='动力类型')),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低价格(万元)')),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高价格(万元)')),
                ('range_km', models.IntegerField(default=400, verbose_name='续航里程(km)')),
                ('battery_capacity', models.DecimalField(decimal_places=2, default=60, max_digits=6, verbose_name='电池容量(kWh)')),
                ('launch_date', models.DateField(verbose_name='上市日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在售')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '车型',
                'verbose_name_plural': '车型',
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('sale_date', models.DateField(verbose_name='销售日期')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价格(万元)')),
                ('quantity', models.IntegerField(default=1, verbose_name='销售数量')),
                ('channel', models.CharField(choices=[('offline', '线下'), ('online', '线上'), ('phone', '电话')], default='offline', max_length=20, verbose_name='销售渠道')),
                ('payment_method', models.CharField(choices=[('full', '全款'), ('loan', '贷款'), ('lease', '租赁')], default='full', max_length=20, verbose_name='付款方式')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额(万元)')),
                ('subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='补贴金额(万元)')),
                ('is_test_drive', models.BooleanField(default=False, verbose_name='是否试驾')),
                ('satisfaction_score', models.IntegerField(default=8, verbose_name='满意度评分(1-10)')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.customer', verbose_name='客户')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.dealer', verbose_name='经销商')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.region', verbose_name='销售区域')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.vehiclemodel', verbose_name='车型')),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('total_sales', models.IntegerField(default=0, verbose_name='总销量')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总销售额(万元)')),
                ('market_share', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='市场份额(%)')),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='平均价格(万元)')),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='增长率(%)')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.brand', verbose_name='品牌')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.region', verbose_name='区域')),
            ],
            options={
                'verbose_name': '市场趋势',
                'verbose_name_plural': '市场趋势',
                'ordering': ['-date'],
                'unique_together': {('date', 'region', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('safety_stock', models.IntegerField(default=10, verbose_name='安全库存')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.dealer', verbose_name='经销商')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.vehiclemodel', verbose_name='车型')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'unique_together': {('vehicle', 'dealer')},
            },
        ),
    ]
